#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Boys Like Girls

# Short bio or description (displayed in the header)
description: poprocková hudební skupina

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/ennie193/ennie193.github.io/blob/master/images/Avatar.jpg?raw=true